Small changes for string parsing
graphql-dotnet/parser pull request #140
Opened 2021-11-05 17:35 UTC by sungam3r

This PR represents a result for the review of #131 . Great job @Shane32 . I did not thoroughly check the entire written code. I confess that it is difficult to read. Many counters, many branches. Nevertheless, the general meaning is well understood. Excellent that you wrote all those tests. In addition to cosmetic edits and comments, I reduced the size of the buffers used on the stack. I do not think that we needed such large buffers.

2021-11-05 17:37 UTC, sungam3r commented on src/GraphQLParser/LexerContext.cs
> +        // TODO: this method can still be optimized no not allocate at all if block string:
@Shane32 I am 100% sure that this can be done, but I was not so brave to do it myself :).

2021-11-05 19:20 UTC, Shane32 requested changes

2021-11-05 19:20 UTC, Shane32 commented on src/GraphQLParser/LexerContext.cs
> +        // 3) has no '\r` characters
```suggestion
        // 1) not too long
        // 2) has no escape sequences
        // 3) has no '\r' characters
        // 4) has no initial whitespace on each line, ignoring the first line (or, has no '\n' characters)
```

2021-11-05 19:20 UTC, Shane32 commented on src/GraphQLParser/LexerContext.cs
> +        // 3) has no '\r` characters
Keep in mind that:

`\"""  test\"""` equals `"  test"` but `\"""\n  test\"""` equals `"\ntest"` (whitespace removed from second sample)

2021-11-05 19:30 UTC, Shane32 commented
> Great job @Shane32 . 

Thanks!  The spec is fairly tricky to implement correctly in an optimized manner.  But I opted for optimization rather than using LINQ or something more readable.  I tried to put some comments in the code to help make it understandable.

Looking back at it now, I don't like that it uses try..catch to catch an overflow and then handle it.  As a general rule of thumb I try not to let any code both generate and catch an exception for two reasons: it significantly slows down execution of code that does not generate an error, and (2) while debugging user code with 'just my code' turned off, the debugger may break on the exception when no error has truly occurred.

If you agree, perhaps you want to modify the PR... up to you.

2021-11-05 20:22 UTC, sungam3r commented on src/GraphQLParser/LexerContext.cs
> +        // 3) has no '\r` characters
```suggestion
        // 3) has no '\r' characters
```

2021-11-05 20:23 UTC, Shane32 approved these changes

2021-11-05 20:27 UTC, sungam3r commented
> Looking back at it now, I don't like that it uses try..catch to catch an overflow and then handle it

Your `ReadBlockString` does not use try/catch, `ReadComment/ReadString` do.

2021-11-05 20:30 UTC, Shane32 commented
> > Looking back at it now, I don't like that it uses try..catch to catch an overflow and then handle it
> 
> Your `ReadBlockString` does not use try/catch, `ReadComment/ReadString` do.

Oh.  Didn't think I would have done that.  Well, sometime we can make an improvement there.

2021-11-05 20:30 UTC, sungam3r commented
In fact, I would not worry because of a potential exception handling slowdown. If an exception is happening, then not so often. In addition, the code performed under the `try/catch` block can work faster so without this block. I once read about such compiler issue.

2021-11-05 20:33 UTC, sungam3r commented
Waiting a bit for https://github.com/graphql/graphql-spec/issues/899 to verify naming.

2021-11-05 20:35 UTC, Shane32 commented
It just really annoys me when I go to debug something, and VS breaks on some internal line of code, which isn't an error.  Which just reminds me that there's a significant performance problem whenever that bit of code gets hit.

2021-11-05 20:50 UTC, sungam3r commented
I know and understand.

2021-11-06 20:21 UTC, sungam3r commented
@Shane32  see https://github.com/graphql/graphql-spec/issues/899#issuecomment-962269529 .  Nevertheless, I will keep `string` and `block string` naming in error messages since there is no `no-block-string` term, only `BlockString` and `StringValue` that **includes** `BlockString`.

2021-11-06 20:22 UTC, merged